const flags = {
    '🇦🇩': { country_code: "AD", country_name: "Andorra", language_code: "ca"},
    '🇦🇪': { country_code: "AE", country_name: "United Arab Emirates", language_code: "ar"},
    '🇦🇫': { country_code: "AF", country_name: "Afghanistan", language_code: "fa"},
    '🇦🇬': { country_code: "AG", country_name: "Antigua and Barbuda", language_code: "en"},
    '🇦🇮': { country_code: "AI", country_name: "Anguilla", language_code: "en"},
    '🇦🇱': { country_code: "AL", country_name: "Albania", language_code: "sq"},
    '🇦🇲': { country_code: "AM", country_name: "Armenia", language_code: "hy"},
    '🇦🇴': { country_code: "AO", country_name: "Angola", language_code: "pt"},
    '🇦🇶': { country_code: "AQ", country_name: "Antarctica", language_code: "en"},
    '🇦🇷': { country_code: "AR", country_name: "Argentina", language_code: "es"},
    '🇦🇸': { country_code: "AS", country_name: "American Samoa", language_code: "en"},
    '🇦🇹': { country_code: "AT", country_name: "Austria", language_code: "de"},
    '🇦🇺': { country_code: "AU", country_name: "Australia", language_code: "en"},
    '🇦🇼': { country_code: "AW", country_name: "Aruba", language_code: "nl"},
    '🇦🇽': { country_code: "AX", country_name: "Aland Islands", language_code: "sv"},
    '🇦🇿': { country_code: "AZ", country_name: "Azerbaijan", language_code: "az"},
    '🇧🇦': { country_code: "BA", country_name: "Bosnia and Herzegovina", language_code: "bs"},
    '🇧🇧': { country_code: "BB", country_name: "Barbados", language_code: "en"},
    '🇧🇩': { country_code: "BD", country_name: "Bangladesh", language_code: "bn"},
    '🇧🇪': { country_code: "BE", country_name: "Belgium", language_code: "nl"},
    '🇧🇫': { country_code: "BF", country_name: "Burkina Faso", language_code: "fr"},
    '🇧🇬': { country_code: "BG", country_name: "Bulgaria", language_code: "bg"},
    '🇧🇭': { country_code: "BH", country_name: "Bahrain", language_code: "ar"},
    '🇧🇮': { country_code: "BI", country_name: "Burundi", language_code: "fr"},
    '🇧🇯': { country_code: "BJ", country_name: "Benin", language_code: "fr"},
    '🏴󠁦󠁲󠁢󠁬󠁿': { country_code: "BL", country_name: "Saint-Barthélemy", language_code: "fr"},
    '🇧🇲': { country_code: "BM", country_name: "Bermuda", language_code: "en"},
    '🇧🇳': { country_code: "BN", country_name: "Brunei Darussalam", language_code: "ms"},
    '🇧🇴': { country_code: "BO", country_name: "Bolivia", language_code: "es"},
    '🇧🇶': { country_code: "BQ", country_name: "Caribbean Netherlands", language_code: "nl"},
    '🇧🇷': { country_code: "BR", country_name: "Brazil", language_code: "pt"},
    '🇧🇸': { country_code: "BS", country_name: "Bahamas", language_code: "en"},
    '🇧🇹': { country_code: "BT", country_name: "Bhutan", language_code: "dz"},
    '🇧🇻': { country_code: "BV", country_name: "Bouvet Island", language_code: "no"},
    '🇧🇼': { country_code: "BW", country_name: "Botswana", language_code: "en"},
    '🇧🇾': { country_code: "BY", country_name: "Belarus", language_code: "be"},
    '🇧🇿': { country_code: "BZ", country_name: "Belize", language_code: "en"},
    '🇨🇦': { country_code: "CA", country_name: "Canada", language_code: "en"},
    '🇨🇨': { country_code: "CC", country_name: "Cocos (Keeling) Islands", language_code: "en"},
    '🇨🇬': { country_code: "CG", country_name: "Republic of the Congo (Congo-Brazzaville)", language_code: "fr"},
    '🇨🇭': { country_code: "CH", country_name: "Switzerland", language_code: "de"},
    '🇨🇮': { country_code: "CI", country_name: "Côte d'Ivoire", language_code: "fr"},
    '🇨🇰': { country_code: "CK", country_name: "Cook Islands", language_code: "en"},
    '🇨🇱': { country_code: "CL", country_name: "Chile", language_code: "es"},
    '🇨🇲': { country_code: "CM", country_name: "Cameroon", language_code: "fr"},
    '🇨🇳': { country_code: "CN", country_name: "China", language_code: "zh-hans"},
    '🇨🇴': { country_code: "CO", country_name: "Colombia", language_code: "es"},
    '🇨🇷': { country_code: "CR", country_name: "Costa Rica", language_code: "es"},
    '🇨🇺': { country_code: "CU", country_name: "Cuba", language_code: "es"},
    '🇨🇻': { country_code: "CV", country_name: "Cabo Verde", language_code: "pt"},
    '🇨🇼': { country_code: "CW", country_name: "Curaçao", language_code: "nl"},
    '🇨🇽': { country_code: "CX", country_name: "Christmas Island", language_code: "en"},
    '🇨🇾': { country_code: "CY", country_name: "Cyprus", language_code: "el"},
    '🇨🇿': { country_code: "CZ", country_name: "Czech Republic", language_code: "cs"},
    '🇩🇪': { country_code: "DE", country_name: "Germany", language_code: "de"},
    '🇩🇯': { country_code: "DJ", country_name: "Djibouti", language_code: "fr"},
    '🇩🇰': { country_code: "DK", country_name: "Denmark", language_code: "da"},
    '🇩🇲': { country_code: "DM", country_name: "Dominica", language_code: "en"},
    '🇩🇴': { country_code: "DO", country_name: "Dominican Republic", language_code: "es"},
    '🇩🇿': { country_code: "DZ", country_name: "Algeria", language_code: "ar"},
    '🇪🇨': { country_code: "EC", country_name: "Ecuador", language_code: "es"},
    '🇪🇪': { country_code: "EE", country_name: "Estonia", language_code: "et"},
    '🇪🇬': { country_code: "EG", country_name: "Egypt", language_code: "ar"},
    '🇪🇭': { country_code: "EH", country_name: "Western Sahara", language_code: "ar"},
    '🇪🇷': { country_code: "ER", country_name: "Eritrea", language_code: "ti"},
    '🇪🇸': { country_code: "ES", country_name: "Spain", language_code: "es"},
    '🇪🇹': { country_code: "ET", country_name: "Ethiopia", language_code: "am"},
    '🇫🇮': { country_code: "FI", country_name: "Finland", language_code: "fi"},
    '🇫🇯': { country_code: "FJ", country_name: "Fiji", language_code: "en"},
    '🇫🇰': { country_code: "FK", country_name: "Falkland Islands", language_code: "en"},
    '🇫🇲': { country_code: "FM", country_name: "Micronesia (Federated States of)", language_code: "en"},
    '🇫🇴': { country_code: "FO", country_name: "Faroe Islands", language_code: "fo"},
    '🇫🇷': { country_code: "FR", country_name: "France", language_code: "fr"},
    '🇬🇦': { country_code: "GA", country_name: "Gabon", language_code: "fr"},
    '🇬🇧': { country_code: "GB", country_name: "United Kingdom", language_code: "en"},
    '🇬🇩': { country_code: "GD", country_name: "Grenada", language_code: "en"},
    '🇬🇪': { country_code: "GE", country_name: "Georgia", language_code: "ka"},
    '🇬🇫': { country_code: "GF", country_name: "French Guiana", language_code: "fr"},
    '🇬🇬': { country_code: "GG", country_name: "Guernsey", language_code: "en"},
    '🇬🇭': { country_code: "GH", country_name: "Ghana", language_code: "en"},
    '🇬🇮': { country_code: "GI", country_name: "Gibraltar", language_code: "en"},
    '🇬🇱': { country_code: "GL", country_name: "Greenland", language_code: "kl"},
    '🇬🇲': { country_code: "GM", country_name: "The Gambia", language_code: "en"},
    '🇬🇳': { country_code: "GN", country_name: "Guinea", language_code: "fr"},
    '🇬🇵': { country_code: "GP", country_name: "Guadeloupe", language_code: "fr"},
    '🇬🇶': { country_code: "GQ", country_name: "Equatorial Guinea", language_code: "es"},
    '🇬🇷': { country_code: "GR", country_name: "Greece", language_code: "el"},
    '🇬🇸': { country_code: "GS", country_name: "South Georgia and the South Sandwich Islands", language_code: "en"},
    '🇬🇹': { country_code: "GT", country_name: "Guatemala", language_code: "es"},
    '🇬🇺': { country_code: "GU", country_name: "Guam", language_code: "en"},
    '🇬🇳': { country_code: "GW", country_name: "Guinea Bissau", language_code: "pt"},
    '🇬🇾': { country_code: "GY", country_name: "Guyana", language_code: "en"},
    '🇭🇰': { country_code: "HK", country_name: "Hong Kong (SAR of China)", language_code: "zh-hant"},
    '🇭🇲': { country_code: "HM", country_name: "Heard Island and McDonald Islands", language_code: "en"},
    '🇭🇳': { country_code: "HN", country_name: "Honduras", language_code: "es"},
    '🇭🇷': { country_code: "HR", country_name: "Croatia", language_code: "hr"},
    '🇭🇹': { country_code: "HT", country_name: "Haiti", language_code: "fr"},
    '🇭🇺': { country_code: "HU", country_name: "Hungary", language_code: "hu"},
    '🇮🇩': { country_code: "ID", country_name: "Indonesia", language_code: "id"},
    '🇮🇪': { country_code: "IE", country_name: "Ireland", language_code: "en"},
    '🇮🇱': { country_code: "IL", country_name: "Israel", language_code: "he"},
    '🇮🇲': { country_code: "IM", country_name: "Isle of Man", language_code: "en"},
    '🇮🇳': { country_code: "IN", country_name: "India", language_code: "hi"},
    '🇮🇴': { country_code: "IO", country_name: "British Indian Ocean Territory", language_code: "en"},
    '🇮🇶': { country_code: "IQ", country_name: "Iraq", language_code: "ar"},
    '🇮🇷': { country_code: "IR", country_name: "Iran", language_code: "fa"},
    '🇮🇸': { country_code: "IS", country_name: "Iceland", language_code: "is"},
    '🇮🇹': { country_code: "IT", country_name: "Italy", language_code: "it"},
    '🇯🇪': { country_code: "JE", country_name: "Jersey", language_code: "en"},
    '🇯🇲': { country_code: "JM", country_name: "Jamaica", language_code: "en"},
    '🇯🇴': { country_code: "JO", country_name: "Jordan", language_code: "ar"},
    '🇯🇵': { country_code: "JP", country_name: "Japan", language_code: "ja"},
    '🇰🇪': { country_code: "KE", country_name: "Kenya", language_code: "sw"},
    '🇰🇬': { country_code: "KG", country_name: "Kyrgyzstan", language_code: "ky"},
    '🇰🇭': { country_code: "KH", country_name: "Cambodia", language_code: "km"},
    '🇰🇮': { country_code: "KI", country_name: "Kiribati", language_code: "en"},
    '🇰🇲': { country_code: "KM", country_name: "Comores", language_code: "ar"},
    '🇰🇳': { country_code: "KN", country_name: "Saint Kitts and Nevis", language_code: "en"},
    '🇰🇵': { country_code: "KP", country_name: "North Korea", language_code: "ko"},
    '🇰🇷': { country_code: "KR", country_name: "South Korea", language_code: "ko"},
    '🇰🇼': { country_code: "KW", country_name: "Kuwait", language_code: "ar"},
    '🇰🇾': { country_code: "KY", country_name: "Cayman Islands", language_code: "en"},
    '🇰🇿': { country_code: "KZ", country_name: "Kazakhstan", language_code: "kk"},
    '🇱🇦': { country_code: "LA", country_name: "Laos", language_code: "lo"},
    '🇱🇧': { country_code: "LB", country_name: "Lebanon", language_code: "ar"},
    '🇱🇨': { country_code: "LC", country_name: "Saint Lucia", language_code: "en"},
    '🇱🇮': { country_code: "LI", country_name: "Liechtenstein", language_code: "de"},
    '🇱🇰': { country_code: "LK", country_name: "Sri Lanka", language_code: "si"},
    '🇱🇷': { country_code: "LR", country_name: "Liberia", language_code: "en"},
    '🇱🇸': { country_code: "LS", country_name: "Lesotho", language_code: "en"},
    '🇱🇹': { country_code: "LT", country_name: "Lithuania", language_code: "lt"},
    '🇱🇺': { country_code: "LU", country_name: "Luxembourg", language_code: "lb"},
    '🇱🇻': { country_code: "LV", country_name: "Latvia", language_code: "lv"},
    '🇱🇾': { country_code: "LY", country_name: "Libya", language_code: "ar"},
    '🇲🇦': { country_code: "MA", country_name: "Morocco", language_code: "fr"},
    '🇲🇨': { country_code: "MC", country_name: "Monaco", language_code: "fr"},
    '🇲🇩': { country_code: "MD", country_name: "Moldova", language_code: "ro"},
    '🇲🇪': { country_code: "ME", country_name: "Montenegro", language_code: "srp"},
    '🇲🇫': { country_code: "MF", country_name: "Saint Martin (French part)", language_code: "fr"},
    '🇲🇬': { country_code: "MG", country_name: "Madagascar", language_code: "mg"},
    '🇲🇭': { country_code: "MH", country_name: "Marshall Islands", language_code: "en"},
    '🇲🇰': { country_code: "MK", country_name: "North Macedonia", language_code: "mk"},
    '🇲🇱': { country_code: "ML", country_name: "Mali", language_code: "fr"},
    '🇲🇲': { country_code: "MM", country_name: "Myanmar", language_code: "my"},
    '🇲🇳': { country_code: "MN", country_name: "Mongolia", language_code: "mn"},
    '🇲🇴': { country_code: "MO", country_name: "Macao (SAR of China)", language_code: "zh-hant"},
    '🇲🇵': { country_code: "MP", country_name: "Northern Mariana Islands", language_code: "en"},
    '🇲🇶': { country_code: "MQ", country_name: "Martinique", language_code: "fr"},
    '🇲🇷': { country_code: "MR", country_name: "Mauritania", language_code: "ar"},
    '🇲🇸': { country_code: "MS", country_name: "Montserrat", language_code: "en"},
    '🇲🇹': { country_code: "MT", country_name: "Malta", language_code: "mt"},
    '🇲🇺': { country_code: "MU", country_name: "Mauritius", language_code: "mfe"},
    '🇲🇻': { country_code: "MV", country_name: "Maldives", language_code: "dv"},
    '🇲🇼': { country_code: "MW", country_name: "Malawi", language_code: "en"},
    '🇲🇽': { country_code: "MX", country_name: "Mexico", language_code: "es"},
    '🇲🇾': { country_code: "MY", country_name: "Malaysia", language_code: "ms"},
    '🇲🇿': { country_code: "MZ", country_name: "Mozambique", language_code: "pt"},
    '🇳🇦': { country_code: "NA", country_name: "Namibia", language_code: "en"},
    '🇳🇨': { country_code: "NC", country_name: "New Caledonia", language_code: "fr"},
    '🇳🇪': { country_code: "NE", country_name: "Niger", language_code: "fr"},
    '🇳🇫': { country_code: "NF", country_name: "Norfolk Island", language_code: "en"},
    '🇳🇬': { country_code: "NG", country_name: "Nigeria", language_code: "en"},
    '🇳🇮': { country_code: "NI", country_name: "Nicaragua", language_code: "es"},
    '🇳🇱': { country_code: "NL", country_name: "The Netherlands", language_code: "nl"},
    '🇳🇴': { country_code: "NO", country_name: "Norway", language_code: "nb"},
    '🇳🇵': { country_code: "NP", country_name: "Nepal", language_code: "ne"},
    '🇳🇷': { country_code: "NR", country_name: "Nauru", language_code: "na"},
    '🇳🇺': { country_code: "NU", country_name: "Niue", language_code: "niu"},
    '🇳🇿': { country_code: "NZ", country_name: "New Zealand", language_code: "mi"},
    '🇴🇲': { country_code: "OM", country_name: "Oman", language_code: "ar"},
    '🇵🇦': { country_code: "PA", country_name: "Panama", language_code: "es"},
    '🇵🇪': { country_code: "PE", country_name: "Peru", language_code: "es"},
    '🇵🇫': { country_code: "PF", country_name: "French Polynesia", language_code: "fr"},
    '🇵🇬': { country_code: "PG", country_name: "Papua New Guinea", language_code: "en"},
    '🇵🇭': { country_code: "PH", country_name: "Philippines", language_code: "en"},
    '🇵🇰': { country_code: "PK", country_name: "Pakistan", language_code: "en"},
    '🇵🇱': { country_code: "PL", country_name: "Poland", language_code: "pl"},
    '🇵🇲': { country_code: "PM", country_name: "Saint Pierre and Miquelon", language_code: "fr"},
    '🇵🇳': { country_code: "PN", country_name: "Pitcairn", language_code: "en"},
    '🇵🇷': { country_code: "PR", country_name: "Puerto Rico", language_code: "es"},
    '🇵🇸': { country_code: "PS", country_name: "Palestinian Territory", language_code: "ar"},
    '🇵🇹': { country_code: "PT", country_name: "Portugal", language_code: "pt"},
    '🇵🇼': { country_code: "PW", country_name: "Palau", language_code: "en"},
    '🇵🇾': { country_code: "PY", country_name: "Paraguay", language_code: "es"},
    '🇶🇦': { country_code: "QA", country_name: "Qatar", language_code: "ar"},
    '🇷🇴': { country_code: "RO", country_name: "Romania", language_code: "ro"},
    '🇷🇸': { country_code: "RS", country_name: "Serbia", language_code: "sr"},
    '🇷🇺': { country_code: "RU", country_name: "Russia", language_code: "ru"},
    '🇷🇼': { country_code: "RW", country_name: "Rwanda", language_code: "rw"},
    '🇸🇦': { country_code: "SA", country_name: "Saudi Arabia", language_code: "ar"},
    '🇸🇧': { country_code: "SB", country_name: "Solomon Islands", language_code: "en"},
    '🇸🇨': { country_code: "SC", country_name: "Seychelles", language_code: "fr"},
    '🇸🇩': { country_code: "SD", country_name: "Sudan", language_code: "ar"},
    '🇸🇪': { country_code: "SE", country_name: "Sweden", language_code: "sv"},
    '🇸🇬': { country_code: "SG", country_name: "Singapore", language_code: "zh-hans"},
    '🇸🇭': { country_code: "SH", country_name: "Saint Helena", language_code: "en"},
    '🇸🇮': { country_code: "SI", country_name: "Slovenia", language_code: "sl"},
    '🇸🇯': { country_code: "SJ", country_name: "Svalbard and Jan Mayen", language_code: "no"},
    '🇸🇰': { country_code: "SK", country_name: "Slovakia", language_code: "sk"},
    '🇸🇱': { country_code: "SL", country_name: "Sierra Leone", language_code: "en"},
    '🇸🇲': { country_code: "SM", country_name: "San Marino", language_code: "it"},
    '🇸🇳': { country_code: "SN", country_name: "Sénégal", language_code: "fr"},
    '🇸🇴': { country_code: "SO", country_name: "Somalia", language_code: "so"},
    '🇸🇷': { country_code: "SR", country_name: "Suriname", language_code: "nl"},
    '🇸🇹': { country_code: "ST", country_name: "São Tomé and Príncipe", language_code: "pt"},
    '🇸🇸': { country_code: "SS", country_name: "South Sudan", language_code: "en"},
    '🇸🇻': { country_code: "SV", country_name: "El Salvador", language_code: "es"},
    '🇸🇽': { country_code: "SX", country_name: "Saint Martin (Dutch part)", language_code: "nl"},
    '🇸🇾': { country_code: "SY", country_name: "Syria", language_code: "ar"},
    '🇸🇿': { country_code: "SZ", country_name: "eSwatini", language_code: "en"},
    '🇹🇨': { country_code: "TC", country_name: "Turks and Caicos Islands", language_code: "en"},
    '🇹🇩': { country_code: "TD", country_name: "Chad", language_code: "fr"},
    '🇹🇬': { country_code: "TG", country_name: "Togo", language_code: "fr"},
    '🇹🇭': { country_code: "TH", country_name: "Thailand", language_code: "th"},
    '🇹🇯': { country_code: "TJ", country_name: "Tajikistan", language_code: "tg"},
    '🇹🇰': { country_code: "TK", country_name: "Tokelau", language_code: "tkl"},
    '🇹🇱': { country_code: "TL", country_name: "Timor-Leste", language_code: "pt"},
    '🇹🇲': { country_code: "TM", country_name: "Turkmenistan", language_code: "tk"},
    '🇹🇳': { country_code: "TN", country_name: "Tunisia", language_code: "ar"},
    '🇹🇴': { country_code: "TO", country_name: "Tonga", language_code: "en"},
    '🇹🇷': { country_code: "TR", country_name: "Turkey", language_code: "tr"},
    '🇹🇹': { country_code: "TT", country_name: "Trinidad and Tobago", language_code: "en"},
    '🇹🇻': { country_code: "TV", country_name: "Tuvalu", language_code: "en"},
    '🇹🇼': { country_code: "TW", country_name: "Taiwan", language_code: "zh-hant"},
    '🇹🇿': { country_code: "TZ", country_name: "Tanzania", language_code: "sw"},
    '🇺🇦': { country_code: "UA", country_name: "Ukraine", language_code: "uk"},
    '🇺🇬': { country_code: "UG", country_name: "Uganda", language_code: "en"},
    '🇺🇸': { country_code: "US", country_name: "United States of America", language_code: "en"},
    '🇺🇾': { country_code: "UY", country_name: "Uruguay", language_code: "es"},
    '🇺🇿': { country_code: "UZ", country_name: "Uzbekistan", language_code: "uz"},
    '🇻🇦': { country_code: "VA", country_name: "City of the Vatican", language_code: "it"},
    '🇻🇨': { country_code: "VC", country_name: "Saint Vincent and the Grenadines", language_code: "en"},
    '🇻🇪': { country_code: "VE", country_name: "Venezuela", language_code: "es"},
    '🇻🇬': { country_code: "VG", country_name: "British Virgin Islands", language_code: "en"},
    '🇻🇮': { country_code: "VI", country_name: "United States Virgin Islands", language_code: "en"},
    '🇻🇳': { country_code: "VN", country_name: "Vietnam", language_code: "vi"},
    '🇻🇺': { country_code: "VU", country_name: "Vanuatu", language_code: "bi"},
    '🇼🇫': { country_code: "WF", country_name: "Wallis and Futuna", language_code: "fr"},
    '🇼🇸': { country_code: "WS", country_name: "Samoa", language_code: "sm"},
    '🇾🇪': { country_code: "YE", country_name: "Yemen", language_code: "ar"},
    '🇾🇹': { country_code: "YT", country_name: "Mayotte", language_code: "fr"},
    '🇿🇦': { country_code: "ZA", country_name: "South Africa", language_code: "en"},
    '🇿🇲': { country_code: "ZM", country_name: "Zambia", language_code: "en"},
    '🇿🇼': { country_code: "ZW", country_name: "Zimbabwe", language_code: "en"},
};

module.exports = {
    convertFlagToText: (flag) => {
        let flagObj = flags[flag];

        if (flagObj) {
            return flagObj.language_code;
        }

        return null;
    }
}